export const STRINGS = {
  parser: {
    title: 'Credit-card transaction classification',
    eyebrow: 'Bank SMS Parser',
    subtitle:
      'Kotlin-native parsing, conservative exclusion, and issuer attribution across the 25 assignment samples.',
    summary: 'Summary',
    results: 'Results',
    details: 'Details',
    topExclusions: 'Top Exclusions',
    included: 'Included',
    excluded: 'Excluded',
    inrDebit: 'INR Debit',
    inrCreditRefund: 'INR Credit/Refund',
    parsingSamples: 'Parsing sample SMS messages...',
    parseErrorFallback: 'Failed to parse SMS samples.',
    unknownMerchant: 'Unknown merchant',
    previewPrefix: 'Preview:',
    samplePrefix: 'Sample',
    close: 'Close',
    decision: 'Decision',
    excludeReason: 'Exclude Reason',
    confidence: 'Confidence',
    rawSms: 'Raw SMS',
    bank: 'Bank',
    amount: 'Amount',
    merchant: 'Merchant',
    type: 'Type',
    cardLastFour: 'Card Last Four',
    date: 'Date',
    none: 'None',
    missing: 'Missing',
    excludedAvatar: 'EX',
    unknownInitials: 'NA',
    unknownKey: 'UNKNOWN',
    cardPrefix: 'Card',
  },
} as const;
